### PR TITLE
Fixed XSS vulnerability in plainText rendered content. Closes #497.

### LINKED ISSUE #497: Whoops – Cross-Site Scripting (XSS)
Product: whoops
Download: https://github.com/filp/whoops/
Vunlerable Version: v2.1.8 and probably prior
Tested Version: commit c871522 
Author: Certimeter S.r.l. (www.certimetergroup.com)

Advisory Details:
A Cross-Site Scripting (XSS) was discovered in “whoops”, which can be exploited to execute arbitrary code.
The content of $preface printed inside /Resources/views/layout.html.php is unescaped.
Exploitation can be possible when the exception stack trace contains the unescaped user input.

Example Request:
`
GET /vendors/?--><script>alert(1)</script> HTTP/1.1`

Response:
```

HTTP/1.0 500 Internal Server Error
Date: Wed, 17 May 2017 17:58:36 GMT
Server: Apache
Cache-Control: max-age=604800
Expires: Wed, 17 May 2017 18:58:36 GMT
Connection: close
Content-Type: text/html;charset=UTF-8

<!DOCTYPE html><!--

Zend_Controller_Router_Exception:
 No route, document, custom route or redirect is matching the request: /vendors/?--><script>alert(1)</script>

Specific ERROR: No route matched the request in file /data/www/public/pimcore/lib/Pimcore.php on line 166
Stack trace:
  1. Zend_Controller_Router_Exception->() /data/www/public/pimcore/lib/Pimcore.php:166
  2. Pimcore->runDispatcher() /data/www/public/pimcore/lib/Pimcore.php:125
  3. Pimcore->run() /data/www/public/index.php:18











--><html>
  <head>
    <meta charset="utf-8">
    <title>Whoops! There was an error.</title>

	[...]
```
Line with injected code:

> No route, document, custom route or redirect is matching the request: /vendors/?--><script>alert(1)</script>

### PR DESCRIPTION
**Pull request by staabm**
Fix not yet verified

### CODE REVIEW

File: src/Whoops/Handler/PrettyPageHandler.php [hunk 1]
```diff
@@ -258,7 +258,7 @@ public function handle()
         $plainTextHandler = new PlainTextHandler();
         $plainTextHandler->setException($this->getException());
         $plainTextHandler->setInspector($this->getInspector());
-        $vars["preface"] = "<!--\n\n\n" . $plainTextHandler->generateResponse() . "\n\n\n\n\n\n\n\n\n\n\n-->";
+        $vars["preface"] = "<!--\n\n\n" .  $this->templateHelper->escape($plainTextHandler->generateResponse()) . "\n\n\n\n\n\n\n\n\n\n\n-->";
```
Comment (GrahamCampbell) [inline src/Whoops/Handler/PrettyPageHandler.php]: One too many spaces here. :P
